### ISSUE TITLE
add marketplace listing

### ISSUE THREAD

**Issue by Bananeweizen** [nodj/AutoDeriv#13]
Please add your plugin to the Eclipse Marketplace. Since the marketplace client allows easy imports of shared favorites lists, I can drop all my colleagues my favorite list, and that should include AutoDeriv.

**Comment by tberne** [comment]
Yes! Please! I also use favorites feature, which is awesome! But I always must install AutoDeriv manually.

**Comment by rtack** [comment]
duplicate of #11

**Comment by Bananeweizen** [comment]
closing, since this is a duplicate, and we meanwhile use oomph to install the plugin.
