### ISSUE TITLE
.gitignore files are created on derived resources

### ISSUE THREAD

**Issue by ZeeD** [nodj/AutoDeriv#24]
Hi.
I've just discovered this project and I'm starting using it.
It works for my purposes, so thanks for your work :)
There is one thing that I don't understand: when I marked a path in the .derived file the resource is marked as derived (good) but also a .gitignore with the resource has been created.
Why? Is there a way to disable this behavior? (I have some autogenerated classes, I want to mark them, but I also want to check in the source repository)

**Comment by nodj** [comment]
Hi @ZeeD 
Full disclaimer, I don't support this repo anymore... 
That being said, there is nothing in the plugin that does git stuff. My guess is that another plugin in eclipse automatically flags derived resources as ignorable in git. I'm not well versed in the Eclipse ecosystem so I cannot guess where / what to look for exactly...

**Comment by nodj** [comment]
Ok so from Stackoverflow, the culprit it EGit ?
https://stackoverflow.com/questions/17748223/egit-and-eclipse-modifies-gitignore-file-but-it-should-not

**Comment by ZeeD** [comment]
Thanks, I missed that property in the settings page
