### ISSUE TITLE
have license in root

### ISSUE THREAD

**Issue by Bananeweizen** [nodj/AutoDeriv#5]
I was just wondering what the license of the plugin is (to decide whether we could bundle it in another eclipse installation). I finally found a license file in the plugin project. Might be useful to copy/move it to the root of the git directory to avoid similar confusion for other visitors.

**Comment by nodj** [comment]
Hello @Bananeweizen and thanks for your insight. I hope AutoDeriv helps you =)
I think it's a good idea, I just pushed the modification. (License is copied, as I prefer to keep the Plugin directory as is)

Thanks !
