### ISSUE TITLE
job label should not include "Job"

### ISSUE THREAD

**Issue by Bananeweizen** [nodj/AutoDeriv#7]
After workspace changes the plugin triggers a job with a title like "AutoDeriv - On Change Event Update Job" or similar (to fast to fully read). "jobs" are an Eclipse internal concept, that end users should not know. Please rephrase that job title to show what it _does_ for the user, e.g. "Marking files derived" or the like.

**Comment by Bananeweizen** [comment]
If I got it right, there is another "Auto Startup Job" from this plugin, where the label should be changed similar.

**Comment by nodj** [comment]
Corrected!
Changes will be reflected in the next release.
Thank you for notifying this :)
